apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
  labels:
    k8s-app: myapp
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: myapp
    spec:
      containers:
      - image: tutum/hello-world
        name: myapp
        ports:
        - containerPort: 80